/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoId = IDL.Nat;
export const UserId = IDL.Principal;
export const Username = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : Username,
  'followers' : IDL.Nat,
  'following' : IDL.Nat,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : UserId,
  'sender' : UserId,
  'videoLink' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
});
export const ContentType = IDL.Variant({
  'video' : IDL.Null,
  'vidle' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'likes' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'uploader' : UserId,
  'uploadTime' : Time,
  'aspectRatio' : IDL.Float64,
});
export const Comment = IDL.Record({
  'text' : IDL.Text,
  'author' : UserId,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'commentOnVideo' : IDL.Func([VideoId, IDL.Text], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationPartners' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMessagesWith' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getMostLikedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVideos' : IDL.Func([UserId], [IDL.Vec(Video)], ['query']),
  'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
  'getVideoComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([VideoId], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        ExternalBlob,
        ContentType,
        IDL.Nat,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoId = IDL.Nat;
  const UserId = IDL.Principal;
  const Username = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : Username,
    'followers' : IDL.Nat,
    'following' : IDL.Nat,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : UserId,
    'sender' : UserId,
    'videoLink' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
  });
  const ContentType = IDL.Variant({ 'video' : IDL.Null, 'vidle' : IDL.Null });
  const Video = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'likes' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'uploader' : UserId,
    'uploadTime' : Time,
    'aspectRatio' : IDL.Float64,
  });
  const Comment = IDL.Record({
    'text' : IDL.Text,
    'author' : UserId,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'commentOnVideo' : IDL.Func([VideoId, IDL.Text], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationPartners' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getMessagesWith' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getMostLikedVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVideos' : IDL.Func([UserId], [IDL.Vec(Video)], ['query']),
    'getVideo' : IDL.Func([VideoId], [IDL.Opt(Video)], ['query']),
    'getVideoComments' : IDL.Func([VideoId], [IDL.Vec(Comment)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([VideoId], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          ExternalBlob,
          ContentType,
          IDL.Nat,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };