/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'text' : string,
  'author' : UserId,
  'timestamp' : Time,
}
export type ContentType = { 'video' : null } |
  { 'vidle' : null };
export type ExternalBlob = Uint8Array;
export interface FriendRequest {
  'status' : FriendRequestStatus,
  'recipient' : UserId,
  'sender' : UserId,
  'timestamp' : Time,
}
export type FriendRequestStatus = { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface Message {
  'content' : string,
  'recipient' : UserId,
  'sender' : UserId,
  'videoLink' : [] | [string],
  'timestamp' : Time,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : Username,
  'followers' : bigint,
  'following' : bigint,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface Video {
  'id' : VideoId,
  'title' : string,
  'contentType' : ContentType,
  'tags' : Array<string>,
  'description' : string,
  'videoFile' : ExternalBlob,
  'likes' : bigint,
  'durationSeconds' : bigint,
  'uploader' : UserId,
  'uploadTime' : Time,
  'aspectRatio' : number,
}
export type VideoId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'commentOnVideo' : ActorMethod<[VideoId, string], undefined>,
  'declineFriendRequest' : ActorMethod<[UserId], undefined>,
  'deleteVideo' : ActorMethod<[VideoId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAcceptedFriendsList' : ActorMethod<[], Array<UserId>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationPartners' : ActorMethod<[], Array<Principal>>,
  'getMessagesWith' : ActorMethod<[UserId], Array<Message>>,
  'getMostLikedVideos' : ActorMethod<[], Array<Video>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<FriendRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideos' : ActorMethod<[UserId], Array<Video>>,
  'getVideo' : ActorMethod<[VideoId], [] | [Video]>,
  'getVideoComments' : ActorMethod<[VideoId], Array<Comment>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[VideoId], undefined>,
  'register' : ActorMethod<[string, string, [] | [ExternalBlob]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendFriendRequest' : ActorMethod<[UserId], undefined>,
  'sendMessage' : ActorMethod<[UserId, string, [] | [string]], undefined>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'unfriend' : ActorMethod<[UserId], undefined>,
  'uploadVideo' : ActorMethod<
    [string, string, Array<string>, ExternalBlob, ContentType, bigint, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];